apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-game
  template:
    metadata:
      labels:
        app: py-game
    spec:
      containers:
        - name: py-game
          image: dileep10/py-game:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: py-game-service
spec:
  selector:
    app: py-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # You can also use LoadBalancer on cloud
